[add] cms_notifications
OCA/website-cms pull request #13
Opened 2017-03-24 08:39 UTC by simahawk

CMS form form for managing personal notifications settings.

Depends on [mail_digest PR](https://github.com/OCA/social/pull/158) and [cms_form PR](https://github.com/OCA/website-cms/pull/9)

2017-03-24 08:44 UTC, simahawk commented
TODO: fix PR dependencies.

2017-05-16 13:13 UTC, guewen reviewed
Performance improvement suggestion.
I like the feature!

2017-05-16 13:13 UTC, guewen commented on cms_notifications/models/res_users.py
> +            item.has_unread_notif = bool(msg_model.search_count(domain))
With a large number of `mail.message`, a `search` with a `limit=1` is drastically faster than a `search_count`. It has to search only 1 line vs all of them.

2017-05-30 11:24 UTC, pedrobaeza commented
Please don't use plurals on module name. cms_notification is good enough I think, or if not, cms_multi_notification.

2017-05-30 12:01 UTC, simahawk commented
@pedrobaeza is it that fundamental? I have it already in production and I'd love to skip a painful migration here :stuck_out_tongue:

2017-05-30 13:03 UTC, pedrobaeza commented
Yeah, I think so. It's already a guideline and avoid typos. You can migrate it very easily with openupgradelib and shell command:
```
from openupgradelib import openupgrade

openupgrade.update_module_names('cms_notifications', 'cms_notification')
```

2017-05-30 13:10 UTC, simahawk commented
@pedrobaeza didn't knew that. TIL thanks :)
I'll rename and squash.

2017-05-30 13:13 UTC, pedrobaeza commented
EDIT: I have fixed the syntax of the code that it was incorrect

2017-06-19 06:53 UTC, simahawk commented
You can hit this button too after OCA/social/pull/158 is merged :heart:

2017-06-21 07:54 UTC, simahawk commented
@pedrobaeza OCA/social#158 merged, any blocker here?

2017-06-21 08:03 UTC, pedrobaeza requested changes
Why don't you use FontAwesome included in Odoo?

2017-06-21 08:03 UTC, pedrobaeza commented on cms_notification/README.rst
> +            Usage
This is incorrectly indented

2017-06-21 08:03 UTC, pedrobaeza commented on cms_notification/i18n/cms_notifications.pot
> +# Translation of Odoo Server.
Remove POT file

2017-06-21 08:03 UTC, pedrobaeza commented on oca_dependencies.txt
> +social https://github.com/camptocamp/social add-mail_digest
This should be changed

2017-06-21 09:08 UTC, simahawk commented
@pedrobaeza font-awesome from odoo is old, at least in v9

2017-06-21 10:09 UTC, pedrobaeza commented
Yeah, but possibly the icons (or similar) used here are in this version, because bundling libraries on each module is very heavy, and more if the use is very light as this one.

2017-06-21 10:17 UTC, simahawk commented
@pedrobaeza they are not. There's no envelope open for instance. This is why I added it. To be honest: I'd say that icons should be updated in OCB. Here, maybe, I can create a custom one...

2017-06-21 10:20 UTC, pedrobaeza commented
OK, what about having a module base_fontawesome with this lib? On v10, we can deprecate it as the version is more modern. Can you obtain the same way of declaring icons with this new module, so you don't have to change anything in this module?

2017-06-21 10:43 UTC, simahawk commented
hmm could be a good idea and allow to reuse it for several v9 modules.

2017-06-21 14:53 UTC, simahawk commented
@pedrobaeza there you go https://github.com/OCA/server-tools/pull/866

2017-11-22 13:32 UTC, simahawk commented
final bits to get this merged: replace oca dependency url as OCA/server-tools#866 has been merged a long time ago.

2017-11-22 14:59 UTC, merged